### ISSUE TITLE
Various Issues (version 0.0.9)

### ISSUE THREAD

**Issue by Techbites457** [AzureDoom/Dark-Waters#1]
**You are probably already aware of some of these issues, but I am posting this on the slim chance you are not. Some of these may have also been due to my testing conditions (void world with /fill ocean)**

Hello! I was testing your mod and found some issues with the mob ai and the hitboxes. A disclaimer: because the computer I'm using is pretty weak, I haven't been able to test this mod in a full world with a natural ocean. I don't know if that is relevant, but it may be an explanation of the weird behavior I'm seeing.

**1. Mob's not attacking**

When I was testing the attack damage of the new mobs, I found that the Manaraw, Sight Hunter, and the Craeken did not seem to want to attack me at all. The Aberration, Miraid, and Mohast did not have this issue (I wanted to get a video, but it wouldn't record).

**2. Aberration and Mohast attack bug**

Both the Aberration and the Mohast attack just fine, but when they do I get teleported on top of them as if I was riding them and immediately dismounted. In version 0.0.8, the Aberration would grab and hold you, which makes me think that the 0.0.9 behavior is a bug (again, sorry for no video).

**3. Hitboxes (might not be fixable)**

The hitboxes for some of the larger mobs seem to be a bit strange.
![2021-11-07_11 55 16](https://user-images.githubusercontent.com/93883938/140660958-97838df3-93eb-41f2-b8ec-b5f58e7daa41.png)

![2021-11-07_11 56 04](https://user-images.githubusercontent.com/93883938/140660966-e93eea0f-6a4b-4d0b-b69d-9849f49968f0.png)
 
The Craeken and the Manaraw have abnormally large hitboxes, and because of collision behaviors melee attacks are very difficult. It also leads to strange collisions, where I push the entity without getting anywhere near the model. I do not have much knowledge about how Minecraft defines hitboxes, so I don't know if this issue can be solved cleanly. This may also be related to issue **1** due to line of sight problems, but that is just speculation.

I know this is early days for this mod, and I love the atmosphere that's being created. Keep up the good work. I cannot wait to see how this mod grows!

**Comment by AzureDoom** [comment]
Hi, thanks for the report!

1) That is correct, those mobs are still heavily WIP and do not have their animations or attack goals yet! That is why they are only spawnable via the eggs and not in Storms yet!

2) No the 0.0.9 attack is correct! The 0.0.8 attack was incorrect and they are meant to pull you to them and attack, the dismount is due to the player and I am still fixing but if you summon a villager, you will see what it is suppose to be doing. The player is trickery to get to say mounted and something I am still tweaking.

3) That is correct, they still need proper hitboxes, the current ones are only just place holders until I get to them!

**Comment by Techbites457** [comment]
Awesome! Glad to see I wasn’t going crazy. As I said above, I can’t wait to see what this mod becomes!
